version: '3.8'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    network_mode: host
    ports:
      - '27017:27017'
    volumes:
      - /data/db
      
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    network_mode: host
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true

volumes:
  db: